spring:
  application:
    name: training
  datasource:
    url: jdbc:postgresql://localhost:15432/training
    username: local
    password: local
  jpa:
    open-in-view: true
    hibernate.ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  docker:
    compose:
      skip:
        in-tests: false